url: https://daniel-burgos.github.io
baseurl: /portfolio/

# Site settings
title: Daniel Casanova Portfolio
email: dubcasanova@gmail.com
description: "Daniel Casanova's Portfolio."


# Team names, titles and social links
people:
- name: 
  pic: 
  position: 
  social:
    - title: 
      url:
    - title:
      url:
    - title:
      url: 
- name: Daniel Casanova
  pic: 2
  position: Instructional Designer/Teacher
  social:
    - title: 
      url: 
    - title: 
      url: 
    - title: 
      url: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: LinkedIn
    url: https://www.linkedin.com/in/daniel-casanova-58248420b/

# Postal address (add as many lines as necessary)
address:
  - line: Houston, TX.
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
