url: https://daniel-burgos.github.io
baseurl: /portfolio/

# Site settings
title: Daniel Casanova Portfolio
email: dubcasanova@gmail.com
description: "Daniel Casanova's Portfolio."


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
- name: Kay Garland
  pic: 2
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: LinkedIn
    url: https://www.linkedin.com/in/daniel-casanova-58248420b/

# Postal address (add as many lines as necessary)
address:
  - line: Houston, TX.
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
